# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

target 'UITestCollecitonVIew' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UITestCollecitonVIew
pod "LAUPickerView", '~> 0.2.0'

  target 'UITestCollecitonVIewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITestCollecitonVIewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
